### ISSUE TITLE
v2.25.0 - Clock module - (timezone: "Europe/Berlin") Returns Undefined 

### ISSUE THREAD

**Issue by wbleek** [MagicMirrorOrg/MagicMirror#3262] opened 2023-11-04 11:25 UTC
After updating to the newest version I get "undefined" with the clock module.

The clock module is the second module in my config.js script.
I only specify 

```
                {
                        module: "clock",
                        position: "top_left",
                        config: {
                                timezone: "Europe/Berlin",
                                showWeek: true
                        }
                },

```
This might be related to issue 3143 https://github.com/MichMich/MagicMirror/issues/3143

**Comment by sdetweil** [comment] 2023-11-04 12:54
I don't see that , for either of these  on 2.25 or on 2.26-develop
```
		},
                {
                        module: "clock",
                        position: "top_left",
                        config: {
                                timezone: "Europe/Berlin",
                                showWeek: true
                        }
                },
		{
			module: "clock",
			disabled: true,
			position: "top_left",
			config:{
				displaySeconds:false,
				timezone:"Europe/Berlin"
			}
		},
```

**Comment by khassel** [comment] 2023-11-04 17:30
I can't reproduce this. Please provide a complete `config.js` example where the error occurs, thanks.

**Comment by khassel** [comment] 2024-01-03 23:13
Closing this because the required information was not provided.

**Closed by khassel** 2024-01-03 23:13 UTC
Labels: trouble shooting, more info needed
